In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

C:\Users\subha\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\subha\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\subha\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [37]:
from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score,confusion_matrix
from sklearn.metrics import roc_curve, roc_auc_score, precision_recall_curve, auc
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('generated_data.xlsx')

In [3]:
df.head()

Brand  Acquisition  Concentration_Class  Concentration  399.40nm  404.39nm  \
0   C11            2                    5              5  0.999980  0.999967   
1   C11            2                    5              5  0.999980  0.999968   
2   C11            2                    5              5  0.999979  0.999968   
3   C11            2                    5              5  0.999979  0.999966   
4   C11            2                    5              5  0.999977  0.999965   

   409.38nm  414.37nm  419.37nm  424.38nm  ...  1020.10nm  1025.55nm  \
0  0.999203  0.992107  0.953222  0.872113  ...   0.477751   0.481703   
1  0.999208  0.992223  0.953823  0.873235  ...   0.478158   0.482184   
2  0.999220  0.992204  0.953378  0.872248  ...   0.477288   0.481155   
3  0.999189  0.992018  0.952935  0.871801  ...   0.477015   0.480936   
4  0.999151  0.991986  0.953458  0.873161  ...   0.477190   0.481269   

   1031.00nm  1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  \
0   0.487756   0.497647   0.513220   0.528185   0.544014   0.562675   
1   0.488387   0.498356   0.514065   0.529189   0.545075   0.563809   
2   0.487180   0.497018   0.512569   0.527521   0.543329   0.561971   
3   0.486965   0.496816   0.512370   0.527352   0.543177   0.561848   
4   0.487589   0.497584   0.513355   0.528691   0.544639   0.563497   

   1063.79nm     Class  
0   0.583122  Rewarewa  
1   0.584472  Rewarewa  
2   0.582424  Rewarewa  
3   0.582337  Rewarewa  
4   0.584432  Rewarewa  

[5 rows x 133 columns]

In [4]:
df['Brand'].value_counts()

C11    7800
C3     6000
C10    4800
C9     3600
C7     3600
C6     3000
C2     1800
C4     1800
C1     1200
C5      600
C8      600
Name: Brand, dtype: int64

In [5]:
df['Acquisition'].value_counts()

2    5800
3    5800
1    5800
4    5800
5    5800
6    5800
Name: Acquisition, dtype: int64

In [6]:
df['Concentration_Class'].value_counts()

5     8700
10    8700
25    8700
50    8700
Name: Concentration_Class, dtype: int64

In [7]:
df['Concentration'].value_counts()

5     8700
10    8700
25    8700
50    8700
Name: Concentration, dtype: int64

In [8]:
df['Class'].value_counts()

Rewarewa        3600
ManukaUMF10     3600
Clover          3600
ManukaUMF5      3600
Multifloral     2400
ManukaUMF15     2400
Manuka          1800
Tawari          1800
ManukaBlend     1800
Rata            1200
Kamahi          1200
Pohu            1200
BB              1200
ManukaUMF20     1200
ManukaUMF13      600
BorageField      600
ManukaUMF12      600
ManukaUMF18      600
ManukaUMF22      600
Honeydew         600
Field+Tawari     600
Name: Class, dtype: int64

In [10]:
Y=df['Concentration']

In [11]:
Y.head()

0    5
1    5
2    5
3    5
4    5
Name: Concentration, dtype: int64

In [12]:
df.drop('Concentration',axis=1,inplace=True)

In [13]:
df.drop('Concentration_Class',axis=1,inplace=True)

In [14]:
df.head()

Brand  Acquisition  399.40nm  404.39nm  409.38nm  414.37nm  419.37nm  \
0   C11            2  0.999980  0.999967  0.999203  0.992107  0.953222   
1   C11            2  0.999980  0.999968  0.999208  0.992223  0.953823   
2   C11            2  0.999979  0.999968  0.999220  0.992204  0.953378   
3   C11            2  0.999979  0.999966  0.999189  0.992018  0.952935   
4   C11            2  0.999977  0.999965  0.999151  0.991986  0.953458   

   424.38nm  429.38nm  434.40nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.872113  0.728557  0.551524  ...   0.477751   0.481703   0.487756   
1  0.873235  0.731307  0.554449  ...   0.478158   0.482184   0.488387   
2  0.872248  0.728564  0.551499  ...   0.477288   0.481155   0.487180   
3  0.871801  0.728091  0.551494  ...   0.477015   0.480936   0.486965   
4  0.873161  0.732385  0.556812  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm     Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122  Rewarewa  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472  Rewarewa  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424  Rewarewa  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337  Rewarewa  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432  Rewarewa  

[5 rows x 131 columns]

In [15]:
# Define the mapping dictionary
brand_mapping = {
    'C1': 1,
    'C2': 2,
    'C3': 3,
    'C4': 4,
    'C5': 5,
    'C6': 6,
    'C7': 7,
    'C8': 8,
    'C9': 9,
    'C10': 10,
    'C11': 11,
}

# Map the values in the 'Brand' column using the mapping dictionary
df['Brand'] = df['Brand'].map(brand_mapping)

In [16]:
df.head()

Brand  Acquisition  399.40nm  404.39nm  409.38nm  414.37nm  419.37nm  \
0     11            2  0.999980  0.999967  0.999203  0.992107  0.953222   
1     11            2  0.999980  0.999968  0.999208  0.992223  0.953823   
2     11            2  0.999979  0.999968  0.999220  0.992204  0.953378   
3     11            2  0.999979  0.999966  0.999189  0.992018  0.952935   
4     11            2  0.999977  0.999965  0.999151  0.991986  0.953458   

   424.38nm  429.38nm  434.40nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.872113  0.728557  0.551524  ...   0.477751   0.481703   0.487756   
1  0.873235  0.731307  0.554449  ...   0.478158   0.482184   0.488387   
2  0.872248  0.728564  0.551499  ...   0.477288   0.481155   0.487180   
3  0.871801  0.728091  0.551494  ...   0.477015   0.480936   0.486965   
4  0.873161  0.732385  0.556812  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm     Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122  Rewarewa  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472  Rewarewa  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424  Rewarewa  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337  Rewarewa  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432  Rewarewa  

[5 rows x 131 columns]

In [17]:
# Initialize the LabelEncoder
label_encoder = LabelEncoder()

In [18]:
# Fit and transform the selected column
df['Class'] = label_encoder.fit_transform(df['Class'])

In [19]:
df.head()

Brand  Acquisition  399.40nm  404.39nm  409.38nm  414.37nm  419.37nm  \
0     11            2  0.999980  0.999967  0.999203  0.992107  0.953222   
1     11            2  0.999980  0.999968  0.999208  0.992223  0.953823   
2     11            2  0.999979  0.999968  0.999220  0.992204  0.953378   
3     11            2  0.999979  0.999966  0.999189  0.992018  0.952935   
4     11            2  0.999977  0.999965  0.999151  0.991986  0.953458   

   424.38nm  429.38nm  434.40nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.872113  0.728557  0.551524  ...   0.477751   0.481703   0.487756   
1  0.873235  0.731307  0.554449  ...   0.478158   0.482184   0.488387   
2  0.872248  0.728564  0.551499  ...   0.477288   0.481155   0.487180   
3  0.871801  0.728091  0.551494  ...   0.477015   0.480936   0.486965   
4  0.873161  0.732385  0.556812  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm  Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122     19  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472     19  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424     19  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337     19  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432     19  

[5 rows x 131 columns]

In [20]:
df['Class'].value_counts()

19    3600
8     3600
2     3600
15    3600
16    2400
11    2400
6     1800
20    1800
7     1800
18    1200
5     1200
17    1200
0     1200
13    1200
10     600
1      600
9      600
12     600
14     600
4      600
3      600
Name: Class, dtype: int64

In [21]:
X=df

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42,shuffle=True)

In [61]:
from sklearn.tree import DecisionTreeClassifier

tree_only=DecisionTreeClassifier(max_depth=9,max_features=8)
tree_only.fit(X_train,y_train)

tree_only.score(X_test,y_test)

0.8929118773946361

In [57]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.996743295019157

In [27]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.9987547892720307

In [30]:
from sklearn import svm
from sklearn.metrics import accuracy_score

clf = svm.SVC(kernel='poly', degree=4) 
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.6441570881226054

In [55]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

# # Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:\n",cm)

# Calculate Cohen's Kappa
cohen_kappa = cohen_kappa_score(y_test, y_pred)
print("Cohen's Kappa:", cohen_kappa)

confusion matrix:
 [[2628    2    0    0]
 [  11 2550    0    0]
 [   0    0 2604    0]
 [   0    0    0 2645]]
Cohen's Kappa: 0.9983396239101351


In [62]:
import numpy as np

# Calculate precision and recall for each class
precision_per_class = precision_score(y_test, y_pred, average=None)
recall_per_class = recall_score(y_test, y_pred, average=None)

# Calculate micro-average precision and recall
micro_precision = precision_score(y_test, y_pred, average='micro')
micro_recall = recall_score(y_test, y_pred, average='micro')

# Calculate macro-average precision and recall
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')

# Calculate weighted-average precision and recall
weighted_precision = precision_score(y_test, y_pred, average='weighted')
weighted_recall = recall_score(y_test, y_pred, average='weighted')

# Print per-class precision and recall
num_classes = len(np.unique(y_test))
for class_label in range(num_classes):
    print(f"Class {class_label}: Precision = {precision_per_class[class_label]}, Recall = {recall_per_class[class_label]}")

print("Micro-Average Precision:", micro_precision)
print("Micro-Average Recall:", micro_recall)
print("Macro-Average Precision:", macro_precision)
print("Macro-Average Recall:", macro_recall)
print("Weighted-Average Precision:", weighted_precision)
print("Weighted-Average Recall:", weighted_recall)

Class 0: Precision = 0.9901849754624387, Recall = 0.9973384030418251
Class 1: Precision = 0.9972462627852084, Recall = 0.9898477157360406
Class 2: Precision = 0.999616122840691, Recall = 1.0
Class 3: Precision = 1.0, Recall = 0.9996219281663516
Micro-Average Precision: 0.996743295019157
Micro-Average Recall: 0.996743295019157
Macro-Average Precision: 0.9967618402720846
Macro-Average Recall: 0.9967020117360543
Weighted-Average Precision: 0.9967561827908324
Weighted-Average Recall: 0.996743295019157


In [63]:
from sklearn.metrics import confusion_matrix, roc_curve, auc, precision_recall_curve, cohen_kappa_score
import numpy as np
import matplotlib.pyplot as plt

# Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Calculate False Positive Rate (FPR) and False Negative Rate (FNR) for each class
num_classes = len(np.unique(y_test))
fpr_per_class = []
fnr_per_class = []
for class_label in range(num_classes):
    tn = np.sum(np.delete(cm, class_label, axis=0)[:, class_label])
    fp = np.sum(cm[:, class_label]) - cm[class_label, class_label]
    tp = cm[class_label, class_label]
    fn = np.sum(np.delete(cm, class_label, axis=1)[class_label, :])
    fpr = fp / (fp + tn)
    fnr = fn / (fn + tp)
    fpr_per_class.append(fpr)
    fnr_per_class.append(fnr)

# Calculate Cohen's Kappa
cohen_kappa = cohen_kappa_score(y_test, y_pred)

print("False Positive Rate per Class:", fpr_per_class)
print("False Negative Rate per Class:", fnr_per_class)
# print("F Beta score per Class:", f_beta_per_class)
print("Cohen's Kappa:", cohen_kappa)


False Positive Rate per Class: [0.5, 0.5, 0.5, nan]
False Negative Rate per Class: [0.002661596958174905, 0.01015228426395939, 0.0, 0.0003780718336483932]
Cohen's Kappa: 0.9956574434399625


C:\Users\subha\AppData\Local\Temp\ipykernel_11112\4186702197.py:17: RuntimeWarning: invalid value encountered in longlong_scalars
  fpr = fp / (fp + tn)


In [64]:
# # Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:\n",cm)

confusion matrix:
 [[2623    7    0    0]
 [  26 2535    0    0]
 [   0    0 2604    0]
 [   0    0    1 2644]]
