# Is your Honey Adulterated?

# Data Cleaning and Visualization

In [498]:
import os # for file access
import pandas as pd # for data processing
import numpy as np # for math processing

# for plotting
import plotly.express as px

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from sklearn.metrics import precision_score, recall_score, f1_score, cohen_kappa_score,confusion_matrix
from sklearn.metrics import roc_curve, roc_auc_score, precision_recall_curve, auc
import matplotlib.pyplot as plt

np.random.seed(33)

In [499]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

from sklearn.cluster import DBSCAN


In [500]:

# Load the dataset
#file = ('D:\Research\Honey Adulteration\new\generated_data.xlsx')
file = ('D:\\Research\\Honey Adulteration\\new\\generated_data.xlsx')
df = pd.read_excel(file)
df.head()

Brand  Acquisition  Concentration_Class  Concentration  399.40nm  404.39nm  \
0   C11            2                    5              5  0.999980  0.999967   
1   C11            2                    5              5  0.999980  0.999968   
2   C11            2                    5              5  0.999979  0.999968   
3   C11            2                    5              5  0.999979  0.999966   
4   C11            2                    5              5  0.999977  0.999965   

   409.38nm  414.37nm  419.37nm  424.38nm  ...  1020.10nm  1025.55nm  \
0  0.999203  0.992107  0.953222  0.872113  ...   0.477751   0.481703   
1  0.999208  0.992223  0.953823  0.873235  ...   0.478158   0.482184   
2  0.999220  0.992204  0.953378  0.872248  ...   0.477288   0.481155   
3  0.999189  0.992018  0.952935  0.871801  ...   0.477015   0.480936   
4  0.999151  0.991986  0.953458  0.873161  ...   0.477190   0.481269   

   1031.00nm  1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  \
0   0.487756   0.497647   0.513220   0.528185   0.544014   0.562675   
1   0.488387   0.498356   0.514065   0.529189   0.545075   0.563809   
2   0.487180   0.497018   0.512569   0.527521   0.543329   0.561971   
3   0.486965   0.496816   0.512370   0.527352   0.543177   0.561848   
4   0.487589   0.497584   0.513355   0.528691   0.544639   0.563497   

   1063.79nm     Class  
0   0.583122  Rewarewa  
1   0.584472  Rewarewa  
2   0.582424  Rewarewa  
3   0.582337  Rewarewa  
4   0.584432  Rewarewa  

[5 rows x 133 columns]

In [501]:
df['Brand'].value_counts()

Brand
C11    7800
C3     6000
C10    4800
C9     3600
C7     3600
C6     3000
C2     1800
C4     1800
C1     1200
C5      600
C8      600
Name: count, dtype: int64

In [502]:
df['Acquisition'].value_counts()

Acquisition
2    5800
3    5800
1    5800
4    5800
5    5800
6    5800
Name: count, dtype: int64

In [503]:
df['Concentration_Class'].value_counts()

Concentration_Class
5     8700
10    8700
25    8700
50    8700
Name: count, dtype: int64

In [504]:
df['Concentration'].value_counts()

Concentration
5     8700
10    8700
25    8700
50    8700
Name: count, dtype: int64

In [505]:
df['Class'].value_counts()

Class
Rewarewa        3600
ManukaUMF10     3600
Clover          3600
ManukaUMF5      3600
Multifloral     2400
ManukaUMF15     2400
Manuka          1800
Tawari          1800
ManukaBlend     1800
Rata            1200
Kamahi          1200
Pohu            1200
BB              1200
ManukaUMF20     1200
ManukaUMF13      600
BorageField      600
ManukaUMF12      600
ManukaUMF18      600
ManukaUMF22      600
Honeydew         600
Field+Tawari     600
Name: count, dtype: int64

In [506]:
df.shape

(34800, 133)

In [507]:
df.dtypes.value_counts()

float64    128
int64        3
object       2
Name: count, dtype: int64

In [508]:
df.head()

Brand  Acquisition  Concentration_Class  Concentration  399.40nm  404.39nm  \
0   C11            2                    5              5  0.999980  0.999967   
1   C11            2                    5              5  0.999980  0.999968   
2   C11            2                    5              5  0.999979  0.999968   
3   C11            2                    5              5  0.999979  0.999966   
4   C11            2                    5              5  0.999977  0.999965   

   409.38nm  414.37nm  419.37nm  424.38nm  ...  1020.10nm  1025.55nm  \
0  0.999203  0.992107  0.953222  0.872113  ...   0.477751   0.481703   
1  0.999208  0.992223  0.953823  0.873235  ...   0.478158   0.482184   
2  0.999220  0.992204  0.953378  0.872248  ...   0.477288   0.481155   
3  0.999189  0.992018  0.952935  0.871801  ...   0.477015   0.480936   
4  0.999151  0.991986  0.953458  0.873161  ...   0.477190   0.481269   

   1031.00nm  1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  \
0   0.487756   0.497647   0.513220   0.528185   0.544014   0.562675   
1   0.488387   0.498356   0.514065   0.529189   0.545075   0.563809   
2   0.487180   0.497018   0.512569   0.527521   0.543329   0.561971   
3   0.486965   0.496816   0.512370   0.527352   0.543177   0.561848   
4   0.487589   0.497584   0.513355   0.528691   0.544639   0.563497   

   1063.79nm     Class  
0   0.583122  Rewarewa  
1   0.584472  Rewarewa  
2   0.582424  Rewarewa  
3   0.582337  Rewarewa  
4   0.584432  Rewarewa  

[5 rows x 133 columns]

In [509]:
Y=df['Concentration']

In [510]:
Y.head()

0    5
1    5
2    5
3    5
4    5
Name: Concentration, dtype: int64

In [511]:
df.drop('Concentration_Class',axis=1,inplace=True)

In [512]:
df.head()

Brand  Acquisition  Concentration  399.40nm  404.39nm  409.38nm  414.37nm  \
0   C11            2              5  0.999980  0.999967  0.999203  0.992107   
1   C11            2              5  0.999980  0.999968  0.999208  0.992223   
2   C11            2              5  0.999979  0.999968  0.999220  0.992204   
3   C11            2              5  0.999979  0.999966  0.999189  0.992018   
4   C11            2              5  0.999977  0.999965  0.999151  0.991986   

   419.37nm  424.38nm  429.38nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.953222  0.872113  0.728557  ...   0.477751   0.481703   0.487756   
1  0.953823  0.873235  0.731307  ...   0.478158   0.482184   0.488387   
2  0.953378  0.872248  0.728564  ...   0.477288   0.481155   0.487180   
3  0.952935  0.871801  0.728091  ...   0.477015   0.480936   0.486965   
4  0.953458  0.873161  0.732385  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm     Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122  Rewarewa  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472  Rewarewa  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424  Rewarewa  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337  Rewarewa  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432  Rewarewa  

[5 rows x 132 columns]

In [513]:
# Define the mapping dictionary
brand_mapping = {
    'C1': 1,
    'C2': 2,
    'C3': 3,
    'C4': 4,
    'C5': 5,
    'C6': 6,
    'C7': 7,
    'C8': 8,
    'C9': 9,
    'C10': 10,
    'C11': 11,
}

# Map the values in the 'Brand' column using the mapping dictionary
df['Brand'] = df['Brand'].map(brand_mapping)

In [514]:
df.head()

Brand  Acquisition  Concentration  399.40nm  404.39nm  409.38nm  414.37nm  \
0     11            2              5  0.999980  0.999967  0.999203  0.992107   
1     11            2              5  0.999980  0.999968  0.999208  0.992223   
2     11            2              5  0.999979  0.999968  0.999220  0.992204   
3     11            2              5  0.999979  0.999966  0.999189  0.992018   
4     11            2              5  0.999977  0.999965  0.999151  0.991986   

   419.37nm  424.38nm  429.38nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.953222  0.872113  0.728557  ...   0.477751   0.481703   0.487756   
1  0.953823  0.873235  0.731307  ...   0.478158   0.482184   0.488387   
2  0.953378  0.872248  0.728564  ...   0.477288   0.481155   0.487180   
3  0.952935  0.871801  0.728091  ...   0.477015   0.480936   0.486965   
4  0.953458  0.873161  0.732385  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm     Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122  Rewarewa  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472  Rewarewa  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424  Rewarewa  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337  Rewarewa  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432  Rewarewa  

[5 rows x 132 columns]

In [515]:
# Initialize the LabelEncoder
label_encoder = LabelEncoder()

In [516]:
# Fit and transform the selected column
df['Class'] = label_encoder.fit_transform(df['Class'])

In [517]:
df.head()

Brand  Acquisition  Concentration  399.40nm  404.39nm  409.38nm  414.37nm  \
0     11            2              5  0.999980  0.999967  0.999203  0.992107   
1     11            2              5  0.999980  0.999968  0.999208  0.992223   
2     11            2              5  0.999979  0.999968  0.999220  0.992204   
3     11            2              5  0.999979  0.999966  0.999189  0.992018   
4     11            2              5  0.999977  0.999965  0.999151  0.991986   

   419.37nm  424.38nm  429.38nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.953222  0.872113  0.728557  ...   0.477751   0.481703   0.487756   
1  0.953823  0.873235  0.731307  ...   0.478158   0.482184   0.488387   
2  0.953378  0.872248  0.728564  ...   0.477288   0.481155   0.487180   
3  0.952935  0.871801  0.728091  ...   0.477015   0.480936   0.486965   
4  0.953458  0.873161  0.732385  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm  Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122     19  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472     19  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424     19  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337     19  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432     19  

[5 rows x 132 columns]

In [518]:
df['Class'].value_counts()

Class
19    3600
8     3600
2     3600
15    3600
16    2400
11    2400
6     1800
20    1800
7     1800
18    1200
5     1200
17    1200
0     1200
13    1200
10     600
1      600
9      600
12     600
14     600
4      600
3      600
Name: count, dtype: int64

In [519]:
df.head()

Brand  Acquisition  Concentration  399.40nm  404.39nm  409.38nm  414.37nm  \
0     11            2              5  0.999980  0.999967  0.999203  0.992107   
1     11            2              5  0.999980  0.999968  0.999208  0.992223   
2     11            2              5  0.999979  0.999968  0.999220  0.992204   
3     11            2              5  0.999979  0.999966  0.999189  0.992018   
4     11            2              5  0.999977  0.999965  0.999151  0.991986   

   419.37nm  424.38nm  429.38nm  ...  1020.10nm  1025.55nm  1031.00nm  \
0  0.953222  0.872113  0.728557  ...   0.477751   0.481703   0.487756   
1  0.953823  0.873235  0.731307  ...   0.478158   0.482184   0.488387   
2  0.953378  0.872248  0.728564  ...   0.477288   0.481155   0.487180   
3  0.952935  0.871801  0.728091  ...   0.477015   0.480936   0.486965   
4  0.953458  0.873161  0.732385  ...   0.477190   0.481269   0.487589   

   1036.46nm  1041.92nm  1047.38nm  1052.85nm  1058.32nm  1063.79nm  Class  
0   0.497647   0.513220   0.528185   0.544014   0.562675   0.583122     19  
1   0.498356   0.514065   0.529189   0.545075   0.563809   0.584472     19  
2   0.497018   0.512569   0.527521   0.543329   0.561971   0.582424     19  
3   0.496816   0.512370   0.527352   0.543177   0.561848   0.582337     19  
4   0.497584   0.513355   0.528691   0.544639   0.563497   0.584432     19  

[5 rows x 132 columns]

In [520]:
df.drop('Concentration',axis=1,inplace=True)

In [521]:
X=df

# Splitting the dataset

In [522]:
from sklearn.model_selection import train_test_split

# 7:3

In [523]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42,shuffle=True)

# LinearRegression

In [524]:
# Initialize the Linear Regression model
model = LinearRegression()


In [525]:

# Fit the model to the training data
model.fit(X_train, y_train)

LinearRegression()

In [526]:

# Make predictions on the testing data
y_pred = model.predict(X_test)

In [527]:

# Calculate Mean Squared Error (MSE) as a measure of model performance
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 1.6076478733345836


# Random Forest Regressor

In [528]:
from sklearn.ensemble import RandomForestRegressor

In [529]:
# Initialize the Random Forest Regressor
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)


In [530]:

# Fit the model to the training data
rf_regressor.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [531]:

# Predict the concentrations on the testing data
y_pred = rf_regressor.predict(X_test)

In [532]:

# Calculate the Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.24939415708812257


# MLP Regressor

In [533]:
from sklearn.neural_network import MLPRegressor

In [534]:
# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [535]:
# Initialize the MLPRegressor (neural network) model
mlp_regressor = MLPRegressor(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', random_state=42)


In [536]:
# Fit the model to the scaled training data
mlp_regressor.fit(X_train_scaled, y_train)


MLPRegressor(hidden_layer_sizes=(100, 50), random_state=42)

In [537]:
# Predict the concentrations on the scaled testing data
y_pred = mlp_regressor.predict(X_test_scaled)

In [538]:
# Calculate the Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.4050728824483903


# SVR regressor

In [539]:
from sklearn.svm import SVR

In [540]:
# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [541]:
# Initialize the SVR model
svr_regressor = SVR(kernel='rbf')



In [542]:

# Fit the model to the scaled training data
svr_regressor.fit(X_train_scaled, y_train)

SVR()

In [543]:

# Predict the concentrations on the scaled testing data
y_pred = svr_regressor.predict(X_test_scaled)

In [544]:

# Calculate the Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 3.777011202384562


# KNN

In [545]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

X_test = X_test.values

y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

c:\Users\swapn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names



0.9987547892720307

In [546]:

# # Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:\n",cm)


confusion matrix:
 [[2628    2    0    0]
 [  11 2550    0    0]
 [   0    0 2604    0]
 [   0    0    0 2645]]


In [547]:
# Extract values from the confusion matrix
true_negatives = cm[0, 0]
false_positives = cm[0, 1]
false_negatives = cm[1, 0]
true_positives = cm[1, 1]


In [548]:

# Calculate False Positive Rate (FPR)
fpr = false_positives / (false_positives + true_negatives)
print("False Positive Rate (FPR):", fpr)

False Positive Rate (FPR): 0.0007604562737642585


In [549]:
# Calculate False Negative Rate (FNR)
fnr = false_negatives / (false_negatives + true_positives)
print("False Negative Rate (FNR):", fnr)

False Negative Rate (FNR): 0.004295197188598204


In [550]:
# Calculate Recall (True Positive Rate)
recall = true_positives / (true_positives + false_negatives)
print("Recall:", recall)

Recall: 0.9957048028114018


In [551]:
# Calculate Precision
precision = true_positives / (true_positives + false_positives)
print("Precision:", precision)

Precision: 0.9992163009404389


In [552]:
from sklearn.metrics import fbeta_score

# Calculate the F-beta score with the 'macro' average option
beta = 2  # You can adjust the value of beta as needed
f_beta_macro = fbeta_score(y_test, y_pred, beta=beta, average='macro')
print(f"F-beta (beta={beta}, average='macro'):", f_beta_macro)


F-beta (beta=2, average='macro'): 0.9987403119719688


In [553]:

# Calculate Cohen's Kappa
cohen_kappa_score(y_test, y_pred)

0.9983396239101351

In [554]:
# F1-score = 2 * (Precision * Recall) / (Precision + Recall)
F1score = 2 * (precision * recall) / (precision + recall)
print("F1-score:", F1score)

F1-score: 0.997457461372971


# 8:2

In [555]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42,shuffle=True)

# KNN

In [556]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

X_test = X_test.values

y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

c:\Users\swapn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names



0.9992816091954023

In [557]:

# # Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:\n",cm)


confusion matrix:
 [[1748    2    0    0]
 [   3 1685    0    0]
 [   0    0 1772    0]
 [   0    0    0 1750]]


In [558]:
# Extract values from the confusion matrix
true_negatives = cm[0, 0]
false_positives = cm[0, 1]
false_negatives = cm[1, 0]
true_positives = cm[1, 1]


In [559]:

# Calculate False Positive Rate (FPR)
fpr = false_positives / (false_positives + true_negatives)
print("False Positive Rate (FPR):", fpr)

False Positive Rate (FPR): 0.001142857142857143


In [560]:
# Calculate False Negative Rate (FNR)
fnr = false_negatives / (false_negatives + true_positives)
print("False Negative Rate (FNR):", fnr)

False Negative Rate (FNR): 0.0017772511848341231


In [561]:
# Calculate Recall (True Positive Rate)
recall = true_positives / (true_positives + false_negatives)
print("Recall:", recall)

Recall: 0.9982227488151659


In [562]:
# Calculate Precision
precision = true_positives / (true_positives + false_positives)
print("Precision:", precision)

Precision: 0.998814463544754


In [563]:
from sklearn.metrics import fbeta_score

# Calculate the F-beta score with the 'macro' average option
beta = 2  # You can adjust the value of beta as needed
f_beta_macro = fbeta_score(y_test, y_pred, beta=beta, average='macro')
print(f"F-beta (beta={beta}, average='macro'):", f_beta_macro)


F-beta (beta=2, average='macro'): 0.9992710091169105


In [564]:

# Calculate Cohen's Kappa
cohen_kappa_score(y_test, y_pred)

0.9990420403879076

In [565]:
# F1-score = 2 * (Precision * Recall) / (Precision + Recall)
F1score = 2 * (precision * recall) / (precision + recall)
print("F1-score:", F1score)

F1-score: 0.9985185185185185


# 9:1

In [566]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.1,random_state=42,shuffle=True)

# KNN

In [567]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors=3)
clf.fit(X_train, y_train)

X_test = X_test.values

y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

c:\Users\swapn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning:

X does not have valid feature names, but KNeighborsClassifier was fitted with feature names



0.9994252873563219

In [568]:

# # Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("confusion matrix:\n",cm)


confusion matrix:
 [[886   0   0   0]
 [  2 855   0   0]
 [  0   0 886   0]
 [  0   0   0 851]]


In [569]:
# Extract values from the confusion matrix
true_negatives = cm[0, 0]
false_positives = cm[0, 1]
false_negatives = cm[1, 0]
true_positives = cm[1, 1]


In [570]:

# Calculate False Positive Rate (FPR)
fpr = false_positives / (false_positives + true_negatives)
print("False Positive Rate (FPR):", fpr)

False Positive Rate (FPR): 0.0


In [571]:
# Calculate False Negative Rate (FNR)
fnr = false_negatives / (false_negatives + true_positives)
print("False Negative Rate (FNR):", fnr)

False Negative Rate (FNR): 0.002333722287047841


In [572]:
# Calculate Recall (True Positive Rate)
recall = true_positives / (true_positives + false_negatives)
print("Recall:", recall)

Recall: 0.9976662777129521


In [573]:
# Calculate Precision
precision = true_positives / (true_positives + false_positives)
print("Precision:", precision)

Precision: 1.0


In [574]:
from sklearn.metrics import fbeta_score

# Calculate the F-beta score with the 'macro' average option
beta = 2  # You can adjust the value of beta as needed
f_beta_macro = fbeta_score(y_test, y_pred, beta=beta, average='macro')
print(f"F-beta (beta={beta}, average='macro'):", f_beta_macro)


F-beta (beta=2, average='macro'): 0.9994202217059975


In [575]:

# Calculate Cohen's Kappa
cohen_kappa_score(y_test, y_pred)

0.9992336236607684

In [576]:
# F1-score = 2 * (Precision * Recall) / (Precision + Recall)
F1score = 2 * (precision * recall) / (precision + recall)
print("F1-score:", F1score)

F1-score: 0.9988317757009346
